### ISSUE TITLE
Param/wildcard for the rest of path

### ISSUE THREAD

**Issue by yglukhov** [kedean/nest#15]
Is there any way to define a route to serve static files recursively? Let's say I have a route `/static/{path}` and I want `{path}` to match all the rest of the url even if it has more than one path component? So that `/static/path/to/myfile.txt` is matched and `path` param would then contain `path/to/myfile.txt`.

**Comment by kedean** [comment]
Theoretically, this should be possible by short-circuiting during matching. Doing it with {var} syntax would create ambiguity between the paths `/static/{var1}/action` and `/static/{path}`, as the router would not know which path to take. Perhaps an additional symbol, like `/static/{path}$` to indicate that the match must run to the end of the string?

I'll consider adding this feature as it would be useful to allow '/' in captured parameters.

**Comment by yglukhov** [comment]
Yes, `/static/{path}$` syntax looks totally reasonable.

**Comment by kedean** [comment]
New functionality has been added to master to allow "greedy routing". The `$` symbol can be added to the end of a path or wildcard declaration to indicate it is greedy, e.g. `/static/{path}$` or `/static/*$`. The `$` must appear at the end of the mapping, or a MappingError is raised.

This feature still needs to be more extensively documented.

**Comment by yglukhov** [comment]
Brilliant! Thank you! There's a slight nuance that I haven't considered earlier however. Since `$` is a valid URL char (as well as `*` btw) it's a bit ambiguous to define a pattern, especially when your URL is meant to end with `$`. This looks like a really rare use case to me, still a more consistent syntax could look like:
`{` + `id` + [`$`] + `}`
where `id` could be _ for current `*` "don't care" meaning (that would be consistent with nim `_` values), and optional `$` indicates that this is the last and greedy match.

Examples:
`/my/{path$}` - matches any path starting with `/my/`. `path` will be set to all the rest of the path.
`/my/{_$}` - same as above, but `_` is not stored in the args.
`/my/{path}` - matches any path with 2 path components. 1st is `my`. `path` is set to 2 path component.
`/my/{_}` - same as above, but `_` is not stored in the args.

In any case, the lib is already really useful as it is, so that's just a tiny suggestion.
